export const DISPLAY_TRANSACTIONS = 'DISPLAY_TRANSACTIONS';
export const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';
export const ADD_STOCK = 'ADD_STOCK';
export const UPDATE_STOCK = 'UPDATE_STOCK';
