export const DISPLAY_TRANSACTIONS = 'DISPLAY_TRANSACTIONS';
export const UPDATE_TRANSACTIONS = 'UPDATE_TRANSACTIONS';
export const ADD_STOCK = 'ADD_STOCK';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const SET_CURRENT = 'SET_CURRENT';
export const GRAB_STOCK_TO_UPDATE = 'GRAB_STOCK_TO_UPDATE';
